# Site settings
title:       Poojan Shah
email:       shahpoojan2004@gmail.com
author:      Poojan Shah
description: "Poojan Shah's Homepage"
baseurl:     ""
url:         ""
header_pages: []

# Optional features
animated:       true
enable_mathjax: true
extended_fonts: true

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - CLAUDE.md
  - vendor
